package core.contracts;


public enum CommandType {
    CREATETEAM,
    SHOWTEAMS,
    CREATEPERSON,
    ADDTEAMMEMBER,
    SHOWTEAMMEMBERS,
    ADDCOMMENT,
    REMOVECOMMENT,
    SHOWUSERS,
    SHOWPERSONACTIVITY,
    SHOWBOARDACTIVITY,
    SHOWBOARDS,
    ASSIGNED,
    UNASSIGNED,
    CREATEBOARD;

}
